const mongoose = require("mongoose");

const ENQUIRY_STATUSES = [
  "New",
  "Contacted",
  "Interested",
  "Not Interested",
  "Converted",
  "Closed",
  // Backward compatibility for older mobile/web clients and existing data
  "In Progress",
  "Dropped",
];

const enquirySchema = new mongoose.Schema(
  {
    enqNo: { type: String }, // Auto-generated by server (company-scoped)
    companyId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "Company",
      index: true,
    },
    userId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
      required: true,
    },
    assignedTo: { type: mongoose.Schema.Types.ObjectId, ref: "User" }, // Assigned staff member
    date: { type: String, required: true }, // YYYY-MM-DD format
    enquiryDateTime: { type: Date, default: Date.now },
    enqBy: { type: String },

    // Customer Details
    enqType: String,
    source: String,
    name: { type: String, required: true },
    mobile: { type: String, required: true },
    email: String,
    altMobile: String,
    address: String,
    image: String, // Store image path or base64 string

    // Product Details
    product: { type: String, required: true },
    variant: String,
    color: String,
    cost: { type: Number, required: true }, // This maps to "Lead Value"
    paymentMethod: String,
    conversionDate: Date, // Track when it became a sale
    refundDate: Date, // Track if sale was revoked

    lastContactedAt: Date,
    callCount: { type: Number, default: 0 },

    status: {
      type: String,
      enum: ENQUIRY_STATUSES,
      default: "New",
    },

    // Denormalized fields for lightning-fast list performance
    lastFollowUpDate: { type: String },
    lastFollowUpStatus: { type: String },
    nextFollowUpDate: { type: String },
    lastActivityAt: { type: Date },

    createdAt: { type: Date, default: Date.now },
  },
  { timestamps: true },
);

// Indexes for performance
enquirySchema.index({ userId: 1, status: 1, createdAt: -1 });
enquirySchema.index({ userId: 1, date: -1 });
enquirySchema.index(
  { companyId: 1, enqNo: 1 },
  {
    unique: true,
    partialFilterExpression: {
      companyId: { $exists: true, $type: "objectId" },
      enqNo: { $exists: true, $type: "string" },
    },
  },
);
enquirySchema.index({ assignedTo: 1, status: 1 });
enquirySchema.index({ assignedTo: 1, date: -1 });
enquirySchema.index({ userId: 1, assignedTo: 1, createdAt: -1 });
enquirySchema.index({ companyId: 1, createdAt: -1 });

// Lightning fast list view index (Multi-tenant + ESR)
enquirySchema.index({ companyId: 1, status: 1, lastActivityAt: -1, createdAt: -1 });
enquirySchema.index({ companyId: 1, assignedTo: 1, status: 1, lastActivityAt: -1, createdAt: -1 });

enquirySchema.index({ companyId: 1, date: 1, createdAt: -1 });
enquirySchema.index({ companyId: 1, assignedTo: 1, date: 1, createdAt: -1 });
enquirySchema.index({ name: "text", mobile: "text", email: "text" });
enquirySchema.index({ mobile: 1 });
enquirySchema.index({ companyId: 1, mobile: 1 });

const Enquiry = mongoose.models.Enquiry || mongoose.model("Enquiry", enquirySchema);

const backfillMissingCompanyIds = async () => {
  try {
    if (mongoose.connection.readyState !== 1) return;
    const UserModel = mongoose.models.User;
    if (!UserModel) return;

    const start = Date.now();
    const maxMs = Number(process.env.BACKFILL_COMPANY_IDS_MAX_MS || 45000);
    while (Date.now() - start < maxMs) {
      const enquiries = await Enquiry.find({
        $or: [{ companyId: { $exists: false } }, { companyId: null }],
      })
        .select("_id userId")
        .limit(1000)
        .lean();

      if (!enquiries.length) break;

      const userIds = [
        ...new Set(
          enquiries
            .map((item) => String(item?.userId || ""))
            .filter((value) => mongoose.Types.ObjectId.isValid(value)),
        ),
      ];

      if (!userIds.length) break;

      const users = await UserModel.find({ _id: { $in: userIds } })
        .select("_id company_id")
        .lean();
      const companyByUserId = new Map(
        users
          .filter((item) => item?.company_id)
          .map((item) => [String(item._id), item.company_id]),
      );

      const ops = enquiries
        .map((item) => {
          const companyId = companyByUserId.get(String(item?.userId || ""));
          if (!companyId) return null;
          return {
            updateOne: {
              filter: { _id: item._id },
              update: { $set: { companyId } },
            },
          };
        })
        .filter(Boolean);

      if (!ops.length) break;
      await Enquiry.bulkWrite(ops, { ordered: false });
    }
  } catch (_error) {
    // ignore startup migration issues
  }
};

const ensureEnquiryIndexes = async () => {
  try {
    if (mongoose.connection.readyState !== 1) return;
    const indexes = await Enquiry.collection.indexes();
    if (indexes.some((idx) => idx.name === "enqNo_1")) {
      await Enquiry.collection.dropIndex("enqNo_1").catch(() => {});
    }
    await backfillMissingCompanyIds();
    await Enquiry.syncIndexes().catch(() => {});
  } catch (_error) {
    // ignore startup index migration issues
  }
};

if (mongoose.connection.readyState === 1) {
  ensureEnquiryIndexes();
} else {
  mongoose.connection.once("connected", ensureEnquiryIndexes);
}

module.exports = Enquiry;
module.exports.ENQUIRY_STATUSES = ENQUIRY_STATUSES;
